[package]
name = "aayojak_server"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.2.4", features = ["postgres", "chrono"] }
chrono = { version= "0.4.38", features=["serde"]}
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
actix-web = "4.9.0"